union SigninLogs,AADNonInteractiveUserSignInLogs
//| where TimeGenerated > ago(30d)
| where isnotempty(UserAgent)
| extend UserAgentDetail = todynamic(parse_user_agent(UserAgent, "browser"))
| extend UserAgentFamily = tostring(parse_json(tostring(UserAgentDetail.Browser)).Family)
| extend UserAgentMajorVersion = toint(parse_json(tostring(UserAgentDetail.Browser)).MajorVersion)
//| summarize count() by UserAgent
